name: DMIDetection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - numpy=1.23.4
  - pandas=1.5.2
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - cudatoolkit=11.6  # Windows 需单独安装 CUDA Toolkit 11.6
  - opencv=4.6.0
  - scikit-learn=1.1.3
  - pip
  - pip:
    - timm==0.6.12